language: R
sudo: false
cache: packages
install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('jlmelville/uwot')"
os:
  - linux
  - osx
disable_homebrew: true
