#
# EDADat Unit Tests
#
context("EDADat")

##############################
# Setup
##############################

# ensure reproducibility
set.seed(1)

#
# generate a single dataset with rows corresponding to:
#
#   y =  x
#   y =  1
#   y = -x
#
# this will then be used for both "dat1" and "dat2", allowing us to easily
# check the expected outputs for various similarity measures.
#
dat <- data.frame(
    id=c('alt1', 'alt2', 'alt3'),
    x=rnorm(3),
    y=c('a', 'b', 'c')
)
rownames(dat) <- paste0('id', 1:3)

# transposed version of data
tdat <- data.table::transpose(dat)
rownames(tdat) <- colnames(dat)
colnames(tdat) <- rownames(dat)

# EDADat instances
df_edat  <- EDADat$new(dat)

tdf_edat <- EDADat$new(dat)
tdf_edat$transpose()

# Matrix input
mat  <- matrix(rnorm(100), 10)

mat_edat  <- EDADat$new(mat)
tmat_edat <- EDADat$new(mat)
tmat_edat$transpose()

# Expected row and column names, as generated by EDADat$format_data
rownames(mat) <- paste0('row_', 1:10)
colnames(mat) <- paste0('col_', 1:10)
tmat <- t(mat)

##############################
# Tests
##############################

# test various construction options
test_that("initialization works", {
    expect_equal(df_edat$dat, dat)

    # test alternate specification of row / column names
    # rownames = 1 / id
    expected <- dat[, -1]
    rownames(expected) <- dat[, 1]

    expect_equal(EDADat$new(dat, row_names=1)$dat, expected)
    expect_equal(EDADat$new(dat, row_names='id')$dat, expected)

    # colnames = 1 / id1
    expected <- dat[-1, ]
    colnames(expected) <- dat[1, ]

    expect_equal(EDADat$new(dat, col_names=1)$dat, expected)
    expect_equal(EDADat$new(dat, col_names='id1')$dat, expected)
})

test_that("transposition works", {
    # matrix input
    expect_equal(mat_edat$dat,  mat)
    expect_equal(mat_edat$tdat, tmat)
    expect_equal(tmat_edat$dat, tmat)

    # data frame input
    expect_equal(df_edat$tdat, tdat)
    expect_equal(tdf_edat$dat, tdat)
    expect_equal(tdf_edat$xid, df_edat$yid)
    expect_equal(tdf_edat$yid, df_edat$xid)
    expect_equal(tdf_edat$xlab, df_edat$ylab)
    expect_equal(tdf_edat$ylab, df_edat$xlab)
})

