#
# EDADat Unit Tests
#
context("EDADat")

##############################
# Setup
##############################

# ensure reproducibility
set.seed(1)

#
# generate a single dataset with rows corresponding to:
#
#   y =  x
#   y =  1
#   y = -x
#
# this will then be used for both "dat1" and "dat2", allowing us to easily
# check the expected outputs for various similarity measures.
#
dat <- data.frame(
    id=c('alt1', 'alt2', 'alt3'),
    var1=rnorm(3),
    var2=c('a', 'b', 'c')
)
rownames(dat) <- paste0('id', 1:3)

# transposed version of data
tdat <- data.table::transpose(dat)
rownames(tdat) <- colnames(dat)
colnames(tdat) <- rownames(dat)

# same as dat, but with stringasfactors set to FALSE
good_dat <- data.frame(
    id=c('alt1', 'alt2', 'alt3'),
    var1=rnorm(3),
    var2=c('a', 'b', 'c'),
    stringsAsFactors=FALSE
)
rownames(good_dat) <- paste0('id', 1:3)

# EDADat instances
df_edat  <- EDADat$new(dat)

tdf_edat <- EDADat$new(dat)
tdf_edat$transpose()

good_df_edat <- EDADat$new(good_dat)

# Matrix input
mat  <- matrix(rnorm(100), 10)

mat_edat  <- EDADat$new(mat)
tmat_edat <- EDADat$new(mat)
tmat_edat$transpose()

# Expected row and column names, as generated by EDADat$format_data
rownames(mat) <- paste0('row_', 1:10)
colnames(mat) <- paste0('col_', 1:10)
tmat <- t(mat)

##############################
# Tests
##############################

# test various construction options
test_that("initialization works", {
    expect_equal(df_edat$dat, dat)

    # test alternate specification of row / column names
    # rownames = 1 / id
    expected <- dat[, -1]
    rownames(expected) <- dat[, 1]

    expect_equal(EDADat$new(dat, row_names=1)$dat, expected)
    expect_equal(EDADat$new(dat, row_names='id')$dat, expected)

    # colnames = 1 / id1
    expected <- dat[-1, ]
    colnames(expected) <- dat[1, ]

    expect_equal(EDADat$new(dat, col_names=1)$dat, expected)
    expect_equal(EDADat$new(dat, col_names='id1')$dat, expected)
})

test_that("edat row/column retrieval works", {
    # retrieve row
    expect_equal(df_edat$get('x', 'id2'),                   as.vector(unlist(dat['id2', ])))
    expect_equal(df_edat$get('y', 'id2', other_axis=TRUE),  as.vector(unlist(dat['id2', ])))
    expect_equal(good_df_edat$get('x', 'id2'),              as.vector(unlist(good_dat['id2', ])))

    # if no specific row/column name is specified, get should return the
    # column or row names, respectively
    expect_equal(df_edat$get('x'), colnames(dat))
    expect_equal(df_edat$get('y'), rownames(dat))
    expect_equal(df_edat$get('x', other_axis=TRUE), rownames(dat))
    expect_equal(df_edat$get('y', other_axis=TRUE), colnames(dat))

    # retrieve col
    expect_equal(df_edat$get('y', 'var2'),                  as.vector(unlist(dat[, 'var2'])))
    expect_equal(df_edat$get('x', 'var2', other_axis=TRUE), as.vector(unlist(dat[, 'var2'])))
    expect_equal(good_df_edat$get('y', 'var2'),             as.vector(unlist(good_dat[, 'var2'])))

    # same thing, but for transposed data
    expect_equal(tmat_edat$get('y', 'col_3'), as.vector(unlist(tmat['col_3', ])))
    expect_equal(tmat_edat$get('x', 'row_3'), as.vector(unlist(tmat[, 'row_3'])))
    expect_equal(tdf_edat$get('y', 'var1'),   as.numeric(tdat['var1', ]))
})

test_that("transposition works", {
    # matrix input
    expect_equal(mat_edat$dat,  mat)
    expect_equal(mat_edat$tdat, tmat)
    expect_equal(tmat_edat$dat, tmat)

    # data frame input
    expect_equal(df_edat$tdat, tdat)
    expect_equal(tdf_edat$dat, tdat)
    expect_equal(tdf_edat$xid, df_edat$yid)
    expect_equal(tdf_edat$yid, df_edat$xid)
    expect_equal(tdf_edat$xlab, df_edat$ylab)
    expect_equal(tdf_edat$ylab, df_edat$xlab)
})

